---
- name: Configurer les bases de données MySQL pour les clients WordPress
  hosts: db_master
  become: true
  tasks:
    - name: Configurer MySQL pour écouter sur toutes les interfaces
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: true
      notify: Redémarrer MySQL

    - name: Créer les bases de données pour les clients
      command: >
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS {{ item.name }}_db;"
      loop: "{{ clients }}"

    - name: Créer les utilisateurs MySQL pour les clients
      command: >
        mysql -u root -e
        "CREATE USER IF NOT EXISTS '{{ item.name }}_user'@'172.20.10.2' IDENTIFIED BY '{{ item.db_pass }}';"
      loop: "{{ clients }}"

    - name: Donner les privilèges aux utilisateurs MySQL
      command: >
        mysql -u root -e
        "GRANT ALL PRIVILEGES ON {{ item.name }}_db.* TO '{{ item.name }}_user'@'172.20.10.2';"
      loop: "{{ clients }}"

    - name: Rafraîchir les privilèges MySQL
      command: mysql -u root -e "FLUSH PRIVILEGES;"

  handlers:
    - name: Redémarrer MySQL
      service:
        name: mysql
        state: restarted
